var vueApp = new Vue({
    el: "#vueApp",

    data: {
        workExperience: [{
            job: "Senior Web Developer",
            place: "Intelitec Solution",
            city: "",
            detail: "Bring to the table win-win survival strategies to ensure proactive domination. At the end of the day, going forward, a new normal that has evolved from generation X is on the runway heading towards a streamlined cloud solution. User generated content in real-time will have multiple touchpoints for offshoring.",
            years: "March 2013 - Present",
            url: "",
            image: "",
        },
        {
            job: "Web Developer",
            place: "Intelitec Solution",
            city: "",
            detail: "Capitalize on low hanging fruit to identify a ballpark value added activity to beta test. Override the digital divide with additional clickthroughs from DevOps. Nanotechnology immersion along the information highway will close the loop on focusing solely on the bottom line.",
            years: "December 2011 - March 2013",
            url: "",
            image: "",
        },
        {
            job: "Junior Web Designer",
            place: "Shout! Media Productions",
            city: "",
            detail: "Podcasting operational change management inside of workflows to establish a framework. Taking seamless key performance indicators offline to maximise the long tail. Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration.",
            years: "July 2010 - December 2011",
            url: "",
            image: "",
        },
        {
            job: "Web Design Intern",
            place: "Shout! Media Productions",
            city: "",
            detail: "Collaboratively administrate empowered markets via plug-and-play networks. Dynamically procrastinate B2C users after installed base benefits. Dramatically visualize customer directed convergence without revolutionary ROI.",
            years: "September 2008 - June 2010",
            url: "",
            image: "",
        },



        ],
        studies: [{
            institute: "University of Colorado Boudeler",
            courses: ['Bachelor of Science'],
            city: "",
            detail: "Computer Science - Web Development Track",
            year: "August 2006 - May 2010",
            gpa: "3.23",
            url: "",
            image: "",
        },
        {
            institute: "James Buchanan School",
            courses: ['Technology Magnet Program'],
            city: "",
            detail: "",
            year: "August 2002 - May 2006",
            gpa: "3.56",
            url: "",
            image: "",
        },
        ],
        workExperiences: [{
            job: "Senior Web Developer",
            place: "Intelitec Solutions",
            city: "",
            detail: "Bring to the table win-win survival strategies to ensure proactive domination. At the end of the day, going forward, a new normal that has evolved from generation X is on the runway heading towards a streamlined cloud solution. User generated content in real-time will have multiple touchpoints for offshoring.",
            year: "March 2013 - Present",
            url: "",
            image: "",
        },
        {
            job: "Web Developer",
            place: "Intelitec Solutions",
            city: "",
            detail: "Capitalize on low hanging fruit to identify a ballpark value added activity to beta test. Override the digital divide with additional clickthroughs from DevOps. Nanotechnology immersion along the information highway will close the loop on focusing solely on the bottom line.",
            year: "December 2011 - March 2013",
            url: "",
            image: "",
        },
        {
            job: "Junior Web Designer",
            place: "Shout! Media Productions",
            city: "",
            detail: "Podcasting operational change management inside of workflows to establish a framework. Taking seamless key performance indicators offline to maximise the long tail. Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration.",
            year: "July 2010 - December 2011",
            url: "",
            image: "",
        },
        {
            job: "Web Design Intern",
            place: "Shout! Media Productions",
            city: "",
            detail: "Collaboratively administrate empowered markets via plug-and-play networks. Dynamically procrastinate B2C users after installed base benefits. Dramatically visualize customer directed convergence without revolutionary ROI.",
            year: "September 2008 - June 2010",
            url: "",
            image: "",
        },
        ],
        abilities: [
            'Mobile-First',
            'Responsive Design',
            'Cross Browser Testing & Debugging',
            'Cross Functional Teams',
            'Agile Development & Scrum'
        ],
        interests: [
            'Apart from being a web developer, I enjoy most of my time being outdoors . In the winter, I am an avid skier and novice ice climber. During the warmer months here in Colorado, I enjoy mountain biking, free climbing, and kayaking.',
            'When forced indoors, I follow a number of sci-fi and fantasy genre movies and television shows, I am an aspiring chef, and I spend a large amount of my free time exploring the latest technology advancements in the front-end web development world.'],
        awards: [
            'Google Analytics Certified Developer',
            'Mobile Web Specialist - Google Certification',
            '1st Place - University of Colorado Boulder - Emerging  Tech Competition 2009',
            '1st Place - University of Colorado Boulder - Adobe Creative Jam 2008 (UI Design Category)',
            '2nd Place - University of Colorado Boulder - Emerging Tech Competition 2008',
            '1st Place - James Buchanan High School - Hackathon 2006',
            '3rd Place - James Buchanan High School - Hackathon 2005',
        ],
    },
});